import React from "react";

import Translate from "react-translate-component";

import {Typography, Row, Col} from "bitshares-ui-style-guide";
const {Title, Paragraph} = Typography;

import ReferralProgramCard from "./ReferralProgramCard";

export default class ReferralProgram extends React.Component {
    render() {
        return (
            <div className={"content padding"}>
                <Row gutter={32}>
                    <Col xs={{span: 24}} lg={{span: 16}}>
                        <Paragraph>
                            We are pleased to announce the launch of the
                            referral program for CryptoBridge users! This begins
                            May 15, 2019 00:00 UTC and it will end on August 15,
                            00:00 UTC. Depending on the feedback we receive from
                            the community, we may renew the program.
                        </Paragraph>

                        <Paragraph>
                            Payouts do happen after a full program period has
                            passed (meaning the first payment will arrive after
                            30 days of this announcement). On June 14, 2019 the
                            first payout will be complete. The payment duration
                            is 3 months, meaning you will be paid for a 3 month
                            duration after a user’s signup.
                        </Paragraph>

                        <Title level={4}>How it works</Title>
                        <Paragraph>
                            For every 1 BTC of volume generated by your
                            referrals, you will be eligible for $2.50 USD worth
                            of BridgeCoin (BCO) with the option to claim or
                            stake these coins from within the web wallet.
                        </Paragraph>

                        <Paragraph>
                            We are further incentivizing participants by
                            providing the option to have the BCO staked
                            immediately at the time of payout. Not only will
                            CryptoBridge pay for the BitShares staking fees for
                            you, but we will also add an extra 10% bonus coins
                            to the stake being created!
                        </Paragraph>
                    </Col>
                    <Col xs={{span: 24}} lg={{span: 8}}>
                        <ReferralProgramCard />
                    </Col>
                </Row>
            </div>
        );
    }
}
